export const GET_FILMS = 'GET_FILMS';
export const SELECT_FILM = 'SELECT_FILM';
export const GET_FILM_CHARS = 'GET_FILM_CHARS';
export const SORT_FILM_CHARS = 'SORT_FILM_CHARS';
export const FILTER_FILM_CHARS_BY_GENDER = 'FILTER_FILM_CHARS_BY_GENDER';
